# Site settings
title: Chem Caddy
email: harry@csswizardry.com
description: ""
baseurl: ""
url: "http://jammnjim50.github.io"

# Build settings
markdown: kramdown
permalink: /:year/:month/:title
paginate: 10
