# Site settings
title: Chem Caddy
email: southfloridapowerwash@yahoo.com
description: ""
baseurl: ""
url: "http://chemcaddy.com"

# Build settings
markdown: kramdown
permalink: /:year/:month/:title
paginate: 10
